name: C Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev

      - name: Build
        run: make

      - name: Run tests
        run: |
          cd test
          chmod +x test_fm.sh
          ./test_fm.sh
